Update `Swap` section
cennznet/app-hub pull request #116
Opened 2022-03-08 07:18 UTC by ken-centrality

## Description

Overhaul the Swap section with new UI plus optimise couple of API queries

Closes #97 
Closes #94 

## Details

#### Changes

- Utilise built-in theming system to determine color palette per section
- Switch to use `Roboto Mono` for numeric text
- Update secondary palette to use full hex code
- Switch to use MUI Dialog to make use of its transition effects

#### Fixes

- Prevent users from typing in `-` in the input
- Avoid hard-coding CPAY Asset ID when fetching gas estimate
- Avoid Info Panel is hidden until `balances` are fetched
- Avoid double calling `fetchExchangeRate` and `fetchTokenAmounts`

#### Adds

- Add `ThemeProvider` and `CssGlobal`
- Add a lighter `TokenInput` component
- Add `big.js`

2022-03-10 21:44 UTC, aidan-starke requested changes
- can you chuck in a bit of whitespace between the blue and black text here?

<img width="352" alt="Screen Shot 2022-03-11 at 9 00 44 AM" src="https://user-images.githubusercontent.com/52016903/157745051-15e88aa1-efb3-422c-ab2e-b20272e3f8e4.png">

- can `utils/swap/index` be deleted?

2022-03-10 22:13 UTC, eupston approved these changes
looks really great! very clean code and definitely learned a thing or two

2022-03-10 22:15 UTC, eupston commented on components/SwapStats.tsx
> +
might be worth just chucking a border radius here to match styling of other components

2022-03-10 23:31 UTC, ken-centrality commented
Ready for round 2 @aidan-starke @eupston

2022-03-10 23:41 UTC, aidan-starke approved these changes

2022-03-10 23:41 UTC, aidan-starke commented
lgtm! might want to change the `^` for `SETTINGS` as well

2022-03-11 00:33 UTC, ken-centrality commented
> lgtm! might want to change the `^` for `SETTINGS` as well

🤦‍♂️ oh duh! it's up now, thanks!

2022-03-11 01:19 UTC, merged