ERC20 dynamic decimals
cennznet/app-hub pull request #184
Opened 2022-05-03 04:38 UTC by eupston

## Description

close #150
close #185 

Updates erc20 token value displayed to dynamically account for token specific decimals

## Details

### Changes

- updates swap/pool/bridge value displayed to account for token decimal number

<img width="688" alt="Screen Shot 2022-05-03 at 4 33 19 PM" src="https://user-images.githubusercontent.com/35315320/166405254-6b843256-810e-4c30-a9ef-dbe758ae5c98.png">
<img width="692" alt="Screen Shot 2022-05-03 at 4 33 29 PM" src="https://user-images.githubusercontent.com/35315320/166405259-beb62ceb-f826-44f0-b4fa-a09d3af7f57e.png">

2022-05-03 18:53 UTC, aidan-starke approved these changes
lgtm!

2022-05-03 18:56 UTC, aidan-starke commented
I noticed #185 while testing it out - pretty sure the issue was there already but maybe you could cover it in this PR?

2022-05-03 20:58 UTC, ken-centrality commented
yeah unfortunately it's a not as simple as changing the `scale` property, #185 was the reason why I didn't do it in the beginning. Have some ideas on how to fix it, will take a look today and give you more details @eupston

2022-05-04 02:48 UTC, ken-centrality commented
@eupston another issue is when you type in the input field, say `.0000005` it will switch to `57`, because it's switched to scientific notation `5e-7`

![Screen Shot 2022-05-04 at 14 47 41](https://user-images.githubusercontent.com/97480229/166617081-aeaeb83a-f065-4323-9783-64f74c5f6029.png)


https://user-images.githubusercontent.com/97480229/166617105-ace137f5-2119-47c1-8402-88cbea67c5ef.mov

2022-05-04 05:42 UTC, ken-centrality commented
okay @eupston @aidan-starke made a few more changes to this PR, fix the issue I reported early. Pretty happy with it, can you guys please give it a spin, and do actual transactions too please.

![Screen Shot 2022-05-04 at 17 39 37](https://user-images.githubusercontent.com/97480229/166628059-7dcd2732-22e9-46b2-8c32-162ef091e64f.png)

2022-05-04 06:01 UTC, eupston commented
yup looks good on all components! 
Also nice too in the pool, cause if you enter a very small ETH amount it converts to under 0.0 CPAY and the form won't allow you to submit, which will prevent failed transaction.

2022-05-04 18:44 UTC, aidan-starke requested changes
Looking good, but sadly pressing MAX on with balance `<0.001` on `swap` still crashes the app.  

works on `pool` though!

<img width="499" alt="Screen Shot 2022-05-05 at 6 39 12 AM" src="https://user-images.githubusercontent.com/52016903/166803477-d03f5b10-82d3-446e-b419-7a96d35f1237.png">

2022-05-04 18:44 UTC, aidan-starke commented on components/BridgeProgress.tsx
>  			</p>
this was fine as is, or you could say `check your balances before you try again`

2022-05-04 18:44 UTC, aidan-starke commented on components/PoolProgress.tsx
>  			</p>
same, revert or `check your balances before you try again`

2022-05-04 18:44 UTC, aidan-starke commented on components/SwapProgress.tsx
>  			</p>
same typo

2022-05-04 23:49 UTC, aidan-starke commented
nice @eupston pressing MAX works, but maybe too well now lol

I was able to submit this transaction, and it said it succeeded, but it [failed](https://uncoverexplorer.com/extrinsic/0x57863f79e9f32625070eab3e7ab505f2b580c7bff56c48bfddb045db30acd239?network=Nikau)

<img width="461" alt="Screen Shot 2022-05-05 at 11 44 46 AM" src="https://user-images.githubusercontent.com/52016903/166842855-fbb64e39-cf39-462a-9e08-0d7fb5ea6a3e.png">

2022-05-04 23:55 UTC, eupston commented
@aidan-starke yes thats the last thing we need to sort is prevent TX for 18 decimal tokens to 4 decimal tokens when the value of opposing token is less then 4 decimal places (0.0001). 

On the pool this works great cause when the value goes under 0.0001 the **min** or **empty** field kicks in preventing the form from being submitted. But on the Swap these don't seem to be kicking in yet.

2022-05-05 03:47 UTC, ken-centrality commented
hmm I still want to have that `>0.0001` display in certain cases. Anyway, tell you what let's merge this in as it's stable enough @eupston and I'll create another PR to bring `<0.0001` back without crashing the `swap`

2022-05-05 03:48 UTC, ken-centrality approved these changes

2022-05-05 03:49 UTC, aidan-starke approved these changes

2022-05-05 04:07 UTC, merged