avoid auto popup of `ensureEthereumChain`
cennznet/app-hub pull request #193
Opened 2022-05-18 22:46 UTC by aidan-starke

## Description

 - closes #189

## Details

#### Changes

 - remove `ensureEthereumChain` from `AppSwitch`
 - `ensureEthereumChain` first if connecting metamask on bridge
 - if on bridge and not connected to ethereum, offer link to switch networks

2022-05-19 04:23 UTC, ken-centrality requested changes
looks good, is this to address Jaffar feedbacks?

2022-05-19 04:23 UTC, ken-centrality commented on providers/MetaMaskWalletProvider.tsx
> +
I think we should move this logic to `SubmitButton` and keep `MetaMaskWalletProvider` unaware of what section it's in

2022-05-22 21:27 UTC, ken-centrality commented
shall we close this in favor of #195 ?

2022-05-22 21:33 UTC, aidan-starke commented
reworked in #195

2022-05-22 21:33 UTC, closed without merging