merge fetchAssetBalances & getBridgeBalances
cennznet/app-hub pull request #58
Opened 2022-02-22 23:37 UTC by aidan-starke

## Description

- merge fetchAssetBalances & getBridgeBalances
- closes #46 
- remove initApi
- closes #47

## Details

#### Changes

- implement new fetchAssetBalances function over whole app
- wrap fetchAssetBalances in updateBalances useCallback() to update balances after a transaction
- add token symbol to balance display in wallet
- format balances to show 4 decimal points or none if whole number
- hide 0 balance assets in wallet

#### Fixes

- as Api is setup on render, balances no longer hang
- onClick in ConnectWalletButton

#### Removes

- initApi Function
- ApiRx

#### Adds

- More assets for Nikau:  DAI & WETH
- SVG's for new assets

2022-02-23 03:05 UTC, ken-centrality requested changes
Nice and clean cut overall, I like how we move a good chunk of logic out of React tree, looks much nicer!

2022-02-23 03:05 UTC, ken-centrality commented on utils/index.ts
> +	balance - Math.round(balance) !== 0 ? balance.toFixed(4) : balance;
as per our Slack convo
- [ ] Add parameter type and return type so it's clear what's the function is doing
- [ ] Add logic to check for balance that is less than 4 dp, in that case output straight as `< 0.0001`
- [ ] Need some unit testing for this function to cover all cases scenario

I also think it's fine to output the number with .0000 at the end, so you don't need to check if the number is integer or not, so `balance - Math.round(balance) !== 0 ? balance.toFixed(4) : balance;` can just be as `balance.toFixed(4)`

2022-02-23 05:54 UTC, aidan-starke commented on components/shared/ConnectWalletButton.tsx
> +				onClick={() => onClick()}
that's what I thought, but it breaks 
<img width="519" alt="Screen Shot 2022-02-23 at 6 45 35 PM" src="https://user-images.githubusercontent.com/52016903/155268255-ce021b8c-df0c-403e-b679-dae0b100e5c4.png">

2022-02-23 05:55 UTC, aidan-starke commented on .env.production
>  NEXT_PUBLIC_API_URL="wss://nikau.centrality.me/public/ws"
yup, should be okay with new changes to fetch genericAsset balances

2022-02-23 07:20 UTC, ken-centrality commented on components/shared/ConnectWalletButton.tsx
> +				onClick={() => onClick()}
I checked, it's type issue, `onClick` of button demands `React.MouseEventHandler<HTMLButtonElement>` but what we pass to it is a global "Function" type which is too generic.

so if you change `onClick` type to `MouseEventHandler<HTMLButtonElement>` then it should work.

pinging @eupston as I've also seen this `onClick` somewhere on your PR too

2022-02-23 23:08 UTC, eupston commented on components/shared/ConnectWalletButton.tsx
> +				onClick={() => onClick()}
will fix in PR 59:
https://github.com/cennznet/app-hub/pull/59

2022-02-24 20:00 UTC, eupston approved these changes
lgtm

2022-02-24 21:50 UTC, ken-centrality approved these changes

2022-02-24 21:50 UTC, merged